// <auto-generated />
namespace WellCastServer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class keyname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(keyname));
        
        string IMigrationMetadata.Id
        {
            get { return "201406231432277_keyname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
